version: '2'

networks:
    bibbox-default-network:
      external: true

services:

  §§INSTANCE-app-mysql-db:
    image: mysql:8
    container_name: §§INSTANCE-app-mysql-db
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    environment:
      - MYSQL_ROOT_PASSWORD=thispasswordisneverusededoutsidethecontainer
      - MYSQL_DATABASE=§§MYSQL_DATABASE_NAME
      - MYSQL_USER=§§MYSQL_DATABASE_USER
      - MYSQL_PASSWORD=§§MYSQL_DATABASE_PASSWORD
    volumes_from: 
      - §§INSTANCE-app-data
    depends_on:
      - §§INSTANCE-app-data

  §§INSTANCE-app-adminer:
    image: adminer
    container_name: §§INSTANCE-app-adminer
    restart: unless-stopped
    networks:
      - bibbox-default-network
    user: root
    ports:
      - "§§PORT1:8080"
    volumes_from:
      - §§INSTANCE-app-data
    depends_on:
      - §§INSTANCE-app-data
      - §§INSTANCE-app-mysql-db


  §§INSTANCE-app-data:
    image: busybox
    container_name: §§INSTANCE-app-data
    volumes:
      - ./data/app-data:/var/app-data
      - ./data/app-config:/var/app-config



      
    
